spring:
  application:
    name: drone-platform

  profiles:
    active: local # local or docker
  docker:
    compose:
      enabled: false # local-> false docker->true
server:
  port: your server port
drone:
  ttl: 60 #sec (1min)
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

aws:
  access:
    key-id: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    role-arn: ${S3_SERVER_ROLE}
    region: ${S3_SERVER_REGION}
    bucket-name: ${S3_BUCKET_NAME}
    sts-duration-seconds: 600

---
---
# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: your sql source
    username: your srl username
    password: your sql password
    driver-class-name: your driver
  data:
    redis:
      host: your redis host
      port: your redis port
      password: your redis password
  app:
    cors:
      allowed-origin: your front end url
---
# docker
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: your sql source
  data:
    redis:
      host: your redis host
      port: your redis port
      password: your redis password
  app:
    cors:
      allowed-origin: your front end url
---
# TEST
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  app:
    cors:
      allowed-origin: your front end url